spring.application.name=ResoPlan
spring.main.web-application-type=none

# Database 
spring.datasource.url=jdbc:h2:file:./data/ResoPlan;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Reso
spring.datasource.password=Plan
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# avoiding JPA cache not working very well with heavy client.
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.properties.hibernate.jdbc.batch_size=0